compute_environment: LOCAL_MACHINE
distributed_type: MULTI_GPU     # 单机多卡模式
fp16: true                     # 或者根据您的 amp 配置设置为 true
machine_rank: 0
main_process_ip: null
main_process_port: null
main_training_function: main
num_machines: 1
num_processes: 2                # 该实例中使用2个进程（对应2张GPU）
gpu_ids: "6,7"                  # 指定使用第几号GPU